### ISSUE TITLE
写入的数据在二次插入后无法复制出来

### ISSUE THREAD

**Issue by yiranshaxiao** [zhang-boyang/MacOS_Monterey_NTFS_mount#1]
系统：macOS Monterey version 12.0.1
移动硬盘： 西部数据 1T
复现步骤：
1. 按照 ```readme``` 操作；
2. 输入命令 ```open /Volumes/WD```；
3. 从mac复制文件A过去，正常；
4. 直接从WD复制文件A回来mac，正常；
5. 弹出移动硬盘；
6. 再插入移动硬盘，重复步骤1、2；
7. 从WD复制文件A回来mac的时候，提示 ```one or more items in 'A' can't be changed because they are in use```，最后的复制结果也是失败的。

**Comment by zhang-boyang** [comment]
> 

Hi,
         So happy someone notices this tool. As you mentioned, I think that may be something wrong with the difference between those two file systems. You can refer to this [question](https://apple.stackexchange.com/questions/136157/mov- file-in-external-hd-greyed-out-and-wont-open-this-item-is-used-by-mac-o) to solve your problem.

Regards
